### ISSUE TITLE
"deleted_by" not properly set when BlameableTrait is inherited

### ISSUE THREAD

**Issue by juventus18** [richan-fongdasen/eloquent-blameable#22]
When `SoftDeletes` is defined in a parent class, the `BlameableTrait->useSoftDeletes()` cannot detect the `SoftDeletes` trait in the children classes. Laravel has some built-in functionality that addresses this by using `class_uses_recursive` function to detect trait usage up the inheritance tree. I'm working on the pull request now to fix this issue.

**Comment by richan-fongdasen** [comment]
Hi @juventus18, thanks for pointing this. It is a confirmed bug and thanks for the PR. I'll merge it as soon as possible.

**Comment by richan-fongdasen** [comment]
A new tag has been released: 1.4.1

Feel free to update the package version.
