### ISSUE TITLE
Unable to add blameable to many to many relationship

### ISSUE THREAD

**Issue by musiwei** [richan-fongdasen/eloquent-blameable#37]
This may not be a plugin issue, but how do we add blameable trait to 'many user to many task' relationship, since there is no model for it? A middle table user_task has been created.

**Comment by richan-fongdasen** [comment]
Hi @musiwei 

Sorry for the very slow response. Unfortunately, this package didn't support being implemented yet in your use case. I would be glad if you can help by providing PR for the feature.

Cheers.
